/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DrainMonitoringPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "DrainMessages": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Drains": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "SensorData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SensorHeartbeat": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SesFromEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}